SELECT DISTINCT
RCCL_FECHA_EMI AS 'Fecha',
RCCL_DIVISION_RCCL AS 'División',
RCCL_SUCURSAL_IMP AS 'Sucursal',
RCCL_TIPO_REC AS 'Tipo',
RCCL_NUMERO_RCCL AS 'Número',
RCCL_CLIENTE AS 'Cliente',
CLIE_NOMBRE AS 'Nombre de cliente',
CTEC_MONEDA AS 'Moneda',
CTEC_IMP_TOT_ORI AS 'Total origen',
CTEC_IMP_TOT_LOC AS 'Total local',
RCCL_COBRADOR AS 'Cobrador',
COBR_NOMBRE AS 'Nombre Cobrador'
FROM CCOB_CTEC
INNER JOIN CCOB_CLIE ON CLIE_CLIENTE = CTEC_CLIENTE
INNER JOIN CCOB_RCCC ON RCCC_CTACTE_CTEC = CTEC_CTACTE_CTEC
INNER JOIN CCOB_RCCL ON RCCL_DIVISION_RCCL = RCCC_DIVISION_RCCL AND RCCL_SUCURSAL_IMP = RCCC_SUCURSAL_RCCL AND RCCL_TIPO_REC = RCCC_TIPO_RCCL AND RCCL_NUMERO_RCCL = RCCC_NUMERO_RCCL
INNER JOIN SIST_COBR ON COBR_COBRADOR = RCCL_COBRADOR
WHERE CTEC_ORIGEN = '2'
AND RCCL_COBRADOR IN ('BA01', 'BA02', 'BA03', 'BA04', 'BA05', 'BA06', 'BA07', 'BA08', 'BA09', 'BA10', 'BA11', 'BA12', 'BA13', 'BA14')