SELECT 
MSVA_FECHA_EMI,
ARTS_ARTICULO_EMP,
MOSD_UNIMED, 
MOSD_CANT_ING,
MOSD_FACTOR_UMS,
(MOSD_CANT_ING * MOSD_FACTOR_UMS) AS Entregaenunidades
FROM STOC_MSVA
INNER JOIN STOC_MSMV
ON MSMV_DIVISION_MSVA = MSVA_DIVISION_MSVA
AND MSMV_SUCURSAL_MSVA = MSVA_SUCURSAL_MSVA
AND MSMV_TIPO_MSVA = MSVA_TIPO_MSVA
AND MSMV_NUMERO_MSVA = MSVA_NUMERO_MSVA
INNER JOIN STOC_MOSD ON MOSD_MOVSTO_MOST = MSMV_MOVSTO_MOST
LEFT JOIN STOC_ARTS ON ARTS_ARTICULO = MOSD_ARTICULO
WHERE MOSD_SIGNO = 'S'