WITH STOCK_TOTAL AS (
    SELECT 
        STDP_ARTICULO,
        SUM(STDP_STOCK_ACT) AS STOCK_TOTAL
    FROM STOC_STDP
    WHERE STDP_DEPOSITO NOT IN (7, 152, 153)
    GROUP BY STDP_ARTICULO
),
RESERVADO_TOTAL AS (
    SELECT
        STDP_ARTICULO,
        SUM(STDP_STRES_PED) AS STOCK_RESERVADO
    FROM STOC_STDP
    WHERE STDP_DEPOSITO NOT IN (7, 152, 153)
    GROUP BY STDP_ARTICULO
),
COMPRAS_REI AS (
    SELECT 
        UPPER(LTRIM(RTRIM(mosd.MOSD_ARTICULO))) AS ART_NORM,
        SUM(mosd.MOSD_CANT_UNISTO)              AS COMPRAS_REI_TOTAL
    FROM STOC_MOSD mosd
    INNER JOIN STOC_MSMV msmv
        ON msmv.MSMV_MOVSTO_MOST = mosd.MOSD_MOVSTO_MOST
    WHERE msmv.MSMV_TIPO_MSVA = 'REI'
    GROUP BY UPPER(LTRIM(RTRIM(mosd.MOSD_ARTICULO)))
),
ARTS_BASE AS (
    SELECT 
        ARTS_ARTICULO,
        ARTS_ARTICULO_EMP,
        ARTS_NOMBRE,
        UPPER(LTRIM(RTRIM(ARTS_ARTICULO))) AS ART_NORM
    FROM STOC_ARTS
),
CCRF_CDPR AS (
    SELECT
        UPPER(LTRIM(RTRIM(c.CCRF_ARTICULO))) AS ART_NORM,
        UPPER(LTRIM(RTRIM(c.CCRF_DIVISION_CDPR))) AS DIV_NORM,
        UPPER(LTRIM(RTRIM(c.CCRF_TIPO_CDPR))) AS TIPO_NORM,
        TRY_CONVERT(BIGINT,
            REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(c.CCRF_NUMERO_CDPR)),'-',''),'.',''),' ','')
        ) AS NUM_NORM,
        c.CCRF_PRE_BRUORI_SI AS PRECIO,
        e.CDPR_FECHA_EMI AS FECHA_EMI
    FROM COMP_CCRF c
    INNER JOIN CPAG_CDPR e
        ON UPPER(LTRIM(RTRIM(e.CDPR_DIVISION_CDPR))) = UPPER(LTRIM(RTRIM(c.CCRF_DIVISION_CDPR)))
        AND UPPER(LTRIM(RTRIM(e.CDPR_TIPO_CDPR))) = UPPER(LTRIM(RTRIM(c.CCRF_TIPO_CDPR)))
        AND TRY_CONVERT(BIGINT,
            REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(e.CDPR_NUMERO_CDPR)),'-',''),'.',''),' ','')
        ) = TRY_CONVERT(BIGINT,
            REPLACE(REPLACE(REPLACE(LTRIM(RTRIM(c.CCRF_NUMERO_CDPR)),'-',''),'.',''),' ','')
        )
),
DP3_ULT AS (
    SELECT ART_NORM, PRECIO AS PRECIO_DP3, FECHA_EMI AS FECHA_DP3
    FROM (
        SELECT
            ART_NORM, PRECIO, FECHA_EMI,
            ROW_NUMBER() OVER (
                PARTITION BY ART_NORM
                ORDER BY FECHA_EMI DESC, NUM_NORM DESC
            ) AS rn
        FROM CCRF_CDPR
        WHERE TIPO_NORM = 'DP3'
    ) x
    WHERE rn = 1
),
FAC_ULT AS (
    SELECT ART_NORM, PRECIO AS PRECIO_FC, FECHA_EMI AS FECHA_FC
    FROM (
        SELECT
            ART_NORM, PRECIO, FECHA_EMI,
            ROW_NUMBER() OVER (
                PARTITION BY ART_NORM
                ORDER BY FECHA_EMI DESC, NUM_NORM DESC
            ) AS rn
        FROM CCRF_CDPR
        WHERE TIPO_NORM LIKE 'FA%' OR TIPO_NORM LIKE 'FB%' OR TIPO_NORM LIKE 'FC%'
    ) y
    WHERE rn = 1
)
SELECT 
    A.ARTS_ARTICULO AS CVRF_ARTICULO,
    A.ARTS_ARTICULO_EMP,
    A.ARTS_NOMBRE,

    ISNULL(SUM(
        CASE 
            WHEN V.CVRF_SIGNO = 'E' THEN -V.CVRF_CANT_UNISTO
            WHEN V.CVRF_SIGNO = 'S' THEN  V.CVRF_CANT_UNISTO
            ELSE 0
        END), 0) AS VENTAS,
    ISNULL(S.STOCK_TOTAL, 0) AS STOCK_TOTAL,
    ISNULL(R.STOCK_RESERVADO, 0) AS STOCK_RESERVADO,
    ISNULL(S.STOCK_TOTAL, 0) - ISNULL(R.STOCK_RESERVADO, 0) AS STOCK_DISPONIBLE,
    ISNULL(C.COMPRAS_REI_TOTAL, 0) AS COMPRAS_REI,
    ISNULL(MAX(FU.PRECIO_FC), 0) AS PRECIO_FACTURA,
    MAX(FU.FECHA_FC) AS FECHA_FC2,
    ISNULL(MAX(DU.PRECIO_DP3), 0) AS PRECIO_DIFERENCIAPRECIO,
    MAX(DU.FECHA_DP3) AS FECHA_DP3,

    CASE 
        WHEN MAX(DU.PRECIO_DP3) IS NOT NULL 
             AND MAX(DU.PRECIO_DP3) <> 0
        THEN ISNULL(MAX(FU.PRECIO_FC),0) + ISNULL(MAX(DU.PRECIO_DP3),0)
        ELSE ISNULL(MAX(FU.PRECIO_FC),0)
    END AS PRECIO_UNITARIO_FINAL

FROM ARTS_BASE A

LEFT JOIN VENT_CVRF V 
    ON A.ARTS_ARTICULO = V.CVRF_ARTICULO 
   AND V.CVRF_MOD_STOCK = '1'

LEFT JOIN STOCK_TOTAL S 
    ON S.STDP_ARTICULO = A.ARTS_ARTICULO

LEFT JOIN RESERVADO_TOTAL R
    ON R.STDP_ARTICULO = A.ARTS_ARTICULO

LEFT JOIN COMPRAS_REI C
    ON C.ART_NORM = A.ART_NORM

LEFT JOIN DP3_ULT DU 
    ON DU.ART_NORM = A.ART_NORM

LEFT JOIN FAC_ULT FU 
    ON FU.ART_NORM = A.ART_NORM

WHERE A.ARTS_ARTICULO IN (
    SELECT ARTS_ARTICULO FROM STOC_ARTS WHERE ARTS_TIPO_ART = 'BAZ'
)

GROUP BY 
    A.ARTS_ARTICULO,
    A.ARTS_ARTICULO_EMP,
    A.ARTS_NOMBRE,
    S.STOCK_TOTAL,
    R.STOCK_RESERVADO,
    C.COMPRAS_REI_TOTAL

ORDER BY A.ARTS_ARTICULO;
