SELECT DISTINCT 
CVCL_FECHA_EMI AS Fecha,
CVCL_DIVISION_CVCL AS División,
CVCL_SUCURSAL_IMP AS Sucursal,
CVCL_TIPO_VAR AS Tipo,
CVCL_NUMERO_CVCL AS Número,
VCTC_FECHA_VTO AS [Fecha de vencimiento original],
VCTC_FECHA_VTO_FIN AS [Fecha de vencimiento financiera],
RASI_SIGNO AS Signo,
CASE WHEN RASI_SIGNO = 'H' THEN -VCTC_SAL_ORI ELSE VCTC_SAL_ORI END AS Saldo,
CASE WHEN RASI_SIGNO = 'H' THEN -VCTC_IMP_ORI ELSE VCTC_IMP_ORI END AS [Importe original],
CTEC_MONEDA AS Moneda,
VCTC_NUM_CUOTA AS Cuota,
CTEC_DESCRIPCION AS Observación,
CVCL_CLIENTE AS Cliente,
CLIE_NOMBRE AS 'Cliente_Nombre',
VEND_NOMBRE AS 'Vendedor_Nombre',
ECTC_VENDEDOR AS Vendedor
FROM CCOB_CVCL
INNER JOIN CCOB_CVCC ON CVCC_DIVISION_CVCL = CVCL_DIVISION_CVCL
AND CVCC_SUCURSAL_CVCL = CVCL_SUCURSAL_IMP
AND CVCC_TIPO_CVCL = CVCL_TIPO_VAR
AND CVCC_NUMERO_CVCL = CVCL_NUMERO_CVCL
INNER JOIN CCOB_VCTC ON VCTC_CTACTE_CTEC = CVCC_CTACTE_CTEC
INNER JOIN CCOB_RACC ON RACC_CTACTE_CTEC = CVCC_CTACTE_CTEC
INNER JOIN SIST_RASI ON RASI_ASIENTO = RACC_ASIENTO
INNER JOIN CCOB_CLIE ON CLIE_CLIENTE = CVCL_CLIENTE
INNER JOIN SIST_DIVI ON DIVI_DIVISION = CVCL_DIVISION_CVCL
INNER JOIN CCOB_ECTC ON ECTC_CTACTE_CTEC = CVCC_CTACTE_CTEC
INNER JOIN SIST_VEND ON VEND_VENDEDOR = ECTC_VENDEDOR
INNER JOIN CCOB_CTEC ON CTEC_CTACTE_CTEC = ECTC_CTACTE_CTEC
WHERE VCTC_SAL_ORI <> 0
AND RASI_RENGLON = '1'
AND CVCL_DIVISION_CVCL IN ('2', '29')
AND ECTC_VENDEDOR IN ('BA01', 'BA02', 'BA03', 'BA04', 'BA05', 'BA06', 'BA07', 'BA08', 'BA09', 'BA10', 'BA11', 'BA12', 'BA13')
UNION ALL
SELECT DISTINCT 
RCCL_FECHA_EMI AS Fecha,
RCCL_DIVISION_RCCL AS División,
RCCL_SUCURSAL_IMP AS Sucursal,
RCCL_TIPO_REC AS Tipo,
RCCL_NUMERO_RCCL AS Número,
RCCL_FECHA_EMI AS [Fecha de vencimiento original],
RCCL_FECHA_EMI AS [Fecha de vencimiento financiera],
'H' AS Signo,
VCTC_SAL_ORI AS Saldo,
VCTC_IMP_ORI AS [Importe original],
CTEC_MONEDA AS Moneda,
'1' AS Cuota,
CTEC_DESCRIPCION AS Observación,
RCCL_CLIENTE AS Cliente,
CLIE_NOMBRE AS 'Cliente_Nombre',
COBR_NOMBRE AS 'Vendedor_Nombre',
RCCL_COBRADOR AS Vendedor
FROM CCOB_RCCL
INNER JOIN CCOB_RCCC ON RCCC_DIVISION_RCCL = RCCL_DIVISION_RCCL
AND RCCC_SUCURSAL_RCCL = RCCL_SUCURSAL_IMP
AND RCCC_TIPO_RCCL = RCCL_TIPO_REC
AND RCCC_NUMERO_RCCL = RCCL_NUMERO_RCCL
INNER JOIN CCOB_VCTC ON VCTC_CTACTE_CTEC = RCCC_CTACTE_CTEC
INNER JOIN CCOB_CTEC ON CTEC_CTACTE_CTEC = RCCC_CTACTE_CTEC
INNER JOIN CCOB_CLIE ON CLIE_CLIENTE = CTEC_CLIENTE
INNER JOIN SIST_COBR ON COBR_COBRADOR = RCCL_COBRADOR
WHERE VCTC_SAL_ORI <> 0
AND RCCC_DIVISION_RCCL IN ('2', '29')
AND RCCL_COBRADOR IN ('BA01', 'BA02', 'BA03', 'BA04', 'BA05', 'BA06', 'BA07', 'BA08', 'BA09', 'BA10', 'BA11', 'BA12', 'BA13')
UNION ALL
SELECT DISTINCT 
OPCL_FECHA_EMI AS Fecha,
OPCL_DIVISION_OPCL AS División,
OPCL_SUCURSAL_IMP AS Sucursal,
OPCL_TIPO_OPCL AS Tipo,
OPCL_NUMERO_OPCL AS Número,
NULL AS [Fecha de vencimiento original],
NULL AS [Fecha de vencimiento financiera],
'D' AS Signo,
VCTC_SAL_ORI AS Saldo,
VCTC_IMP_ORI AS [Importe original],
CTEC_MONEDA AS Moneda,
'1' AS Cuota,
CTEC_DESCRIPCION AS Observación,
OPCL_CLIENTE AS Cliente,
CLIE_NOMBRE AS 'Cliente_Nombre',
NULL AS 'Vendedor_Nombre',
NULL AS Vendedor
FROM CCOB_OPCL
INNER JOIN CCOB_OPCC
ON OPCC_DIVISION_OPCL = OPCL_DIVISION_OPCL
AND OPCC_SUCURSAL_OPCL = OPCL_SUCURSAL_IMP
AND OPCC_TIPO_OPCL = OPCL_TIPO_OPCL
AND OPCC_NUMERO_OPCL = OPCL_NUMERO_OPCL
INNER JOIN CCOB_VCTC ON VCTC_CTACTE_CTEC = OPCC_CTACTE_CTEC
INNER JOIN CCOB_CTEC ON CTEC_CTACTE_CTEC = OPCC_CTACTE_CTEC
INNER JOIN CCOB_CLIE ON CLIE_CLIENTE = CTEC_CLIENTE
WHERE VCTC_SAL_ORI <> 0
AND OPCC_DIVISION_OPCL IN ('2', '29')